name: Publish client

on:
  push:
    paths:
      - 'docs/v1.yaml'

jobs:
  publish: 
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '15.x'
          registry-url: 'https://npm.pkg.github.com'
          always-auth: true
          scope: '@uniwise'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - uses: mikefarah/yq@v4.10.0
      
      - name: Version
        run: |
          new_version=$(cat ../docs/v1.yaml | yq .info.version)
          echo "New version\: $new_version"  
          yarn version --new-version "$new_version" --no-git-tag-version

      - name: Publish
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}