name: Linting

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Linting: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install PHP CodeSniffer
        run: |
          curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
          php phpcs.phar --version

      - name: Run PHP CodeSniffer
        run: |
          files=$(git diff-tree --pretty="" --name-only --no-commit-id --diff-filter=d -r ${{ github.event.pull_request.base.sha }}..${{ github.event.after }} -- '**.php')
          if [ ! -z "$files" ]; then
              php phpcs.phar --standard=PSR12 $files
          fi